In [1]:
from openbb import obb

if 'info' in obb.reference:
    obj = obb.reference["info"]["extensions"]["openbb_provider_extension"]
    print([item for item in obj if "tdx" in item])

symbols = "601919,600519,000001,00300"
symbols_a = "601919,600519,000001,600325,600028,600036,430047"
symbol_a = "000001"
symbol_hk = "01658"
provider = "tdxquant"
start_date="2025-09-08"
end_date="2025-12-31"

Extensions to add: tdxquant@0.1.23
Extensions to remove: tdxquant@0.1.22

Building...
['tdxquant@0.1.23']

## 1. 股票相关模型 (Equity Models)
### 1.1 Equity Historical Price (股票历史价格)

In [2]:
obb.equity.price.historical(symbol=symbol_a, provider=provider, use_cache=False, start_date=start_date, end_date=end_date).to_dataframe().tail()

TQ数据接口初始化成功，使用路径: C:\Users\roger\src\openbb\tdx\openbb_tdx\utils\helpers.py
TQ数据连接已关闭

,open,high,low,close,volume,amount,change,change_percent
date,,,,,,,,
2026-04-13,5.85,5.86,5.77,5.83,174104992.0,101136.83,0.02,0.344234
2026-04-14,5.80,5.81,5.76,5.78,135035696.0,78000.90,-0.05,-0.857633
2026-04-15,5.76,5.77,5.68,5.69,187819520.0,107187.45,-0.09,-1.557093
2026-04-16,5.67,5.68,5.64,5.66,149625376.0,84635.68,-0.03,-0.527241
2026-04-17,5.67,5.67,5.56,5.57,171670832.0,96060.45,-0.09,-1.590106

### 1.2 Equity Quote (股票实时报价)

In [2]:
obb.equity.price.quote(symbols, provider=provider).to_dataframe().head()

TQ数据接口初始化成功，使用路径: C:\Users\roger\src\openbb\tdx\openbb_tdx\models\equity_quote.py

,symbol,name,exchange,bid,bid_size,ask,ask_size,market_center,last_price,last_size,open,high,low,close,volume,exchange_volume,prev_close,change,change_percent
0,601919,Stock 601919,上海交易所,14.72,6040,14.73,1264,TdxQuant,14.72,7569,14.88,14.91,14.65,14.72,641119,641119,14.92,-0.01,0.00
1,600519,Stock 600519,上海交易所,1407.24,127,1407.27,1,TdxQuant,1407.24,835,1400.00,1421.00,1399.87,1407.24,96824,96824,1462.84,0.38,0.04
2,000001,Stock 000001,深圳交易所,11.01,1006,11.02,5400,TdxQuant,11.01,6940,11.09,11.11,10.99,11.01,722530,722530,11.09,0.00,0.09
3,00300,Stock 00300,香港交易所,0.00,0,0.00,0,TdxQuant,89.40,294000,88.30,89.55,87.70,89.40,4876949,4876949,88.30,0.00,0.39

### 1.3 Historical Dividends (历史分红)

In [7]:
obb.equity.fundamental.dividends(symbol=symbol_a, provider=provider, use_cache=False).to_dataframe().head()

2026-04-18 10:33:33,309 - openbb_tdx.models.equity_dividends - INFO - Retrieved 31 dividend records for 000001
2026-04-18 10:33:33,311 - openbb_tdx.models.equity_dividends - INFO - Transformed 31 dividend records.

,symbol,ex_dividend_date,dividend_type,rights_issue_ratio,amount,bonus_share_ratio
0,000001,1990-03-01,除权除息,0.1,NaN,NaN
1,000001,1991-05-02,除权除息,NaN,0.3,0.40
2,000001,1991-08-17,除权除息,NaN,NaN,1.00
3,000001,1992-03-23,除权除息,NaN,0.2,0.50
4,000001,1993-05-24,除权除息,0.1,0.3,0.85

### 1.4 Equity Profile (股权资料)

In [2]:
obb.equity.profile(symbol="00005", provider=provider, use_cache=True).to_dataframe().tail()

TQ数据接口初始化成功，使用路径: C:\Users\roger\src\openbb\tdx\openbb_tdx\models\equity_profile.py

,symbol,name,employees,sector,listed_date,total_assets,total_liabilities,revenue,net_income,shares_outstanding,...,J_mggjj,J_mgjzc2,J_gdqyb,J_gdrs,J_HalfYearFlag,tdx_dycode,rs_hycode_sim,blockzscode,underly_setcode,underly_code
0,00005,汇丰控股,1718356,银行,1980-01-02,0.0,19822500.0,6827400.0,2110200.0,0.0,...,0.00,89.81,0.06,0.00,0,-1,108001,882081,0,

### 1.4 Equity Search (股票搜索)

In [5]:
# A-shares symbols
obb.equity.search(query="", market="5", provider=provider).to_dataframe()

2026-04-18 12:58:26,070 - openbb_tdx.models.equity_search - INFO - Equity Search Raw data length from TdxQuant: 5515

         symbol   name exchange
0     000001.SZ   平安银行       SZ
1     000002.SZ   万 科Ａ       SZ
2     000004.SZ  *ST国华       SZ
3     000006.SZ   深振业Ａ       SZ
4     000007.SZ    全新好       SZ
...         ...    ...      ...
5510  920992.BJ   中科美菱      NaN
5511  920125.BJ    鸿仕达      NaN
5512  920156.BJ   海昌智能      NaN
5513  920186.BJ    中科仪      NaN
5514  920191.BJ   瑞尔竞达      NaN

[5515 rows x 3 columns]

In [2]:
# Hong Kong symbols
obb.equity.search(query="", market="102", provider=provider).to_dataframe()

2026-04-18 16:29:53,715 - openbb_tdx.models.equity_search - INFO - Equity Search Raw data length from TdxQuant: 3254

TQ数据接口初始化成功，使用路径: C:\Users\roger\src\openbb\tdx\openbb_tdx\models\equity_search.py

         symbol name exchange
0      00001.HK            HK
1      00002.HK            HK
2      00003.HK            HK
3      00004.HK            HK
4      00005.HK            HK
...         ...  ...      ...
3249  03277H.OT           NaN
3250  06051F.OT           NaN
3251  06656F.OT           NaN
3252  06656H.OT           NaN
3253  07489F.OT           NaN

[3254 rows x 3 columns]

## 2. 财务报表模型 (Financial Statement Models)
### 2.1 Key Metrics (关键指标)

Key Metrics is under `obb.equity.fundamental.metrics`.

In [3]:
obb.equity.fundamental.metrics(symbol=symbol_a, provider=provider).to_dataframe().head()

TQ数据接口初始化成功，使用路径: C:\Users\roger\src\openbb\tdx\openbb_tdx\models\equity_key_metrics.py
TQ数据连接已关闭

,symbol,period_ending,fiscal_year,fiscal_period,currency,market_cap,pe_ratio,forward_pe,eps,price_to_sales,...,return_on_equity,dividend_yield,enterprise_value,ev_to_sales,beta,year_high,year_low,working_capital,operating_cash_flow,ebit_margin
0,000001,2026-03-21,2026,Q1,CNY,2.136590e+12,5.01,5.01,2.2,162550.022063,...,0.077348,0.0541,2.136550e+12,162546.994644,0.19,13.09,10.29,0.0,31585800.0,0.235343

### 2.2 Balance Sheet (资产负债表)

In [3]:
obb.equity.fundamental.balance(symbol=symbol_a, period="quarter", limit=5,provider=provider).to_dataframe().head()

2026-04-19 12:51:45,979 - openbb_tdx.utils.helpers - INFO - Fetching balance_sheet data for 000001 with limit 5 and use_cache=True
2026-04-19 12:51:45,982 - mysharelib.blob_cache - INFO - Generating new quarter data for 000001...

TQ数据接口初始化成功，使用路径: C:\Users\roger\src\openbb\tdx\openbb_tdx\utils\helpers.py
TQ数据连接已关闭

,period_ending,fiscal_period,fiscal_year,cash_and_cash_equivalents,short_term_investments,cash_and_short_term_investments,accounts_receivable,net_receivables,inventory,total_current_assets,...,deferred_tax_liabilities_non_current,other_non_current_liabilities,additional_paid_in_capital,surplus_reserve,treasury_stock,foreign_currency_translation,non_recurring_items_adjustment,total_parent_equity,accumulated_other_comprehensive_income,total_debt
0,2025-12-31,Q4,2025,3.979300e+11,7.651010e+11,1.163031e+12,0.0,0.0,0.0,0.0,...,0,0,80641998848,10780999680,0,0,0,551183974400,136000000,0
1,2025-09-30,Q3,2025,3.933140e+11,6.984870e+11,1.091801e+12,0.0,0.0,0.0,0.0,...,0,0,80637001728,10780999680,0,0,0,517929992192,691000000,0
2,2025-06-30,Q2,2025,4.029850e+11,7.148950e+11,1.117880e+12,0.0,0.0,0.0,0.0,...,0,0,80701997056,10780999680,0,0,0,510062002176,1647000064,0
3,2025-03-31,Q1,2025,4.658550e+11,5.324490e+11,9.983040e+11,0.0,0.0,0.0,0.0,...,0,0,80709001216,10780999680,0,0,0,506111983616,1328999936,0
4,2024-12-31,Q4,2024,4.010630e+11,6.295710e+11,1.030634e+12,0.0,0.0,0.0,0.0,...,0,0,80712998912,10780999680,0,0,0,494841987072,2127000064,0

### 2.2 Income Statement (利润表)

In [3]:
obb.equity.fundamental.income(symbol=symbol_a, provider=provider).to_dataframe()

2026-04-19 13:04:30,560 - openbb_tdx.utils.helpers - INFO - Fetching income_statement data for 000001 with limit 5 and use_cache=True
2026-04-19 13:04:30,563 - mysharelib.blob_cache - INFO - Generating new annual data for 000001.SZ...

TQ数据接口初始化成功，使用路径: C:\Users\roger\src\openbb\tdx\openbb_tdx\utils\helpers.py
TQ数据连接已关闭

,period_ending,fiscal_period,fiscal_year,revenue,operating_income,net_income,net_income_from_continuing_operations,net_income_attributable_to_common_shareholders,consolidated_net_income,basic_earnings_per_share,...,depreciation_and_amortization,ebit,ebitda,weighted_average_basic_shares_outstanding,return_on_equity,net_profit_margin,gross_margin,revenue_growth,net_income_growth,ebitda_margin
0,2025-12-31,Q4,2025,3.077400e+10,5.311000e+09,4.294000e+09,4.355000e+09,4.262400e+10,4.263300e+10,2.07,...,160000000.0,0.0,0.0,1.940592e+10,7.74,0.139533,0.0,-10.40,-4.21,0.0
1,2024-12-31,Q4,2024,3.511300e+10,7.337000e+09,4.779000e+09,5.090000e+09,4.483800e+10,4.450800e+10,2.15,...,489000000.0,0.0,0.0,1.940592e+10,8.99,0.136103,0.0,-10.93,-4.19,0.0
2,2023-12-31,Q4,2023,3.706500e+10,8.881000e+09,6.820000e+09,6.863000e+09,4.643100e+10,4.645500e+10,2.25,...,77000000.0,0.0,0.0,1.940592e+10,9.84,0.184001,0.0,-8.45,2.06,0.0
3,2022-12-31,Q4,2022,4.163000e+10,1.118000e+10,8.857000e+09,8.810000e+09,4.540700e+10,4.551600e+10,2.20,...,-35000000.0,0.0,0.0,1.940592e+10,10.47,0.212755,0.0,6.21,25.26,0.0
4,2021-12-31,Q4,2021,4.219300e+10,9.156000e+09,7.201000e+09,7.238000e+09,3.623000e+10,3.633600e+10,1.73,...,0.0,0.0,0.0,1.940592e+10,9.19,0.170668,0.0,10.32,25.61,0.0

### 2.3 Cash Flow Statement (现金流量表)

In [5]:
obb.equity.fundamental.cash(symbol=symbol_a, provider=provider).to_dataframe().head()

2026-04-19 13:05:21,310 - openbb_tdx.utils.helpers - INFO - Fetching cash_flow data for 000001 with limit 5 and use_cache=True
2026-04-19 13:05:21,313 - mysharelib.blob_cache - INFO - Generating new annual data for 000001.SZ...

TQ数据接口初始化成功，使用路径: C:\Users\roger\src\openbb\tdx\openbb_tdx\utils\helpers.py
TQ数据连接已关闭

,period_ending,fiscal_period,fiscal_year,net_income,depreciation_and_amortization,net_cash_from_operating_activities,operating_cash_flow,net_cash_from_investing_activities,net_cash_from_financing_activities,net_change_in_cash_and_equivalents,...,loss_on_scrapping_of_fixed_assets,loss_on_fair_value_changes,financial_expenses,investment_loss,decrease_in_deferred_tax_assets,increase_in_deferred_tax_liabilities,decrease_in_inventory,decrease_in_operating_receivables,increase_in_operating_payables,other_operating_cash_adjustments
0,2025-12-31,Q4,2025,4.263300e+10,160000000.0,3.158580e+11,3.158580e+11,-7.903600e+10,-1.492360e+11,8.568900e+10,...,0,1484000000,0,-32689999872,2718000128,0,0,-12364999680,256763002880,0
1,2024-12-31,Q4,2024,4.450800e+10,489000000.0,6.333600e+10,6.333600e+10,-3.185900e+10,-7.393300e+10,-4.127300e+10,...,0,-6184000000,0,-36707000320,-6506999808,0,0,-202984996864,199898005504,0
2,2023-12-31,Q4,2023,4.645500e+10,77000000.0,9.246100e+10,9.246100e+10,-2.614200e+10,8.089000e+09,7.589300e+10,...,0,-10728999936,0,-37302001664,-1536000000,0,0,-177434001408,190777999360,0
3,2022-12-31,Q4,2022,4.551600e+10,-35000000.0,1.345720e+11,1.345720e+11,1.785800e+10,-1.614050e+11,-2.896000e+09,...,0,3579000064,0,-34211000320,0,-4648000000,0,-463014985728,490376986624,22368999424
4,2021-12-31,Q4,2021,3.633600e+10,0.0,-1.927330e+11,-1.927330e+11,-4.045500e+10,1.810640e+11,-5.372800e+10,...,0,-2734000128,0,-32988999680,0,-1143000064,0,-500983005184,207707996160,24952000512