In [6]:
from openbb import obb

if 'info' in obb.reference:
    obj = obb.reference["info"]["extensions"]["openbb_provider_extension"]
    print([item for item in obj if "tdx" in item])

symbols = "601919,600519,000001,00300"
symbols_a = "601919,600519,000001,600325,600028,600036,430047"
symbol_a = "000001"
symbol_hk = "01658"
provider = "tdxquant"
start_date="2025-09-08"
end_date="2025-12-31"

['tdxquant@0.1.8']

## 1. 股票相关模型 (Equity Models)
### 1.1 Equity Historical Price (股票历史价格)

In [2]:
obb.equity.price.historical(symbol=symbol_a, provider=provider, use_cache=False, start_date=start_date, end_date=end_date).to_dataframe().tail()

TQ数据接口初始化成功，使用路径: C:\Users\roger\src\openbb\tdx\openbb_tdx\utils\helpers.py
TQ数据连接已关闭

,open,high,low,close,volume,amount,change,change_percent
date,,,,,,,,
2026-04-13,5.85,5.86,5.77,5.83,174104992.0,101136.83,0.02,0.344234
2026-04-14,5.80,5.81,5.76,5.78,135035696.0,78000.90,-0.05,-0.857633
2026-04-15,5.76,5.77,5.68,5.69,187819520.0,107187.45,-0.09,-1.557093
2026-04-16,5.67,5.68,5.64,5.66,149625376.0,84635.68,-0.03,-0.527241
2026-04-17,5.67,5.67,5.56,5.57,171670832.0,96060.45,-0.09,-1.590106

### 1.2 Equity Quote (股票实时报价)

In [2]:
obb.equity.price.quote(symbols, provider=provider).to_dataframe().head()

TQ数据接口初始化成功，使用路径: C:\Users\roger\src\openbb\tdx\openbb_tdx\models\equity_quote.py

,symbol,name,exchange,bid,bid_size,ask,ask_size,market_center,last_price,last_size,open,high,low,close,volume,exchange_volume,prev_close,change,change_percent
0,601919,Stock 601919,上海交易所,14.72,6040,14.73,1264,TdxQuant,14.72,7569,14.88,14.91,14.65,14.72,641119,641119,14.92,-0.01,0.00
1,600519,Stock 600519,上海交易所,1407.24,127,1407.27,1,TdxQuant,1407.24,835,1400.00,1421.00,1399.87,1407.24,96824,96824,1462.84,0.38,0.04
2,000001,Stock 000001,深圳交易所,11.01,1006,11.02,5400,TdxQuant,11.01,6940,11.09,11.11,10.99,11.01,722530,722530,11.09,0.00,0.09
3,00300,Stock 00300,香港交易所,0.00,0,0.00,0,TdxQuant,89.40,294000,88.30,89.55,87.70,89.40,4876949,4876949,88.30,0.00,0.39

### 1.3 Historical Dividends (历史分红)

In [7]:
obb.equity.fundamental.dividends(symbol=symbol_a, provider=provider, use_cache=False).to_dataframe().head()

2026-04-18 10:33:33,309 - openbb_tdx.models.equity_dividends - INFO - Retrieved 31 dividend records for 000001
2026-04-18 10:33:33,311 - openbb_tdx.models.equity_dividends - INFO - Transformed 31 dividend records.

,symbol,ex_dividend_date,dividend_type,rights_issue_ratio,amount,bonus_share_ratio
0,000001,1990-03-01,除权除息,0.1,NaN,NaN
1,000001,1991-05-02,除权除息,NaN,0.3,0.40
2,000001,1991-08-17,除权除息,NaN,NaN,1.00
3,000001,1992-03-23,除权除息,NaN,0.2,0.50
4,000001,1993-05-24,除权除息,0.1,0.3,0.85

### 1.6 Equity Profile (股权资料)

In [ ]:
obb.equity.profile(symbol="00005", provider='akshare', use_cache=True).to_dataframe().tail()